repos:
   - repo: https://github.com/astral-sh/ruff-pre-commit
     rev: v0.14.0
     hooks:
        - id: ruff  # Linter
          args: [--fix]  # Ensure fixes are applied
        - id: ruff-format  # Formatter

   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: 'v1.18.2'  
     hooks:
        - id: mypy